package org.mym.prettylog.data;

/**
 * This is a sample random text to test long logs. The text content is not reviewed.
 * <p>
 * Generated by http://cn.lipsum.com/, please visit this site for more details.
 * <p>
 * Created by muyangmin on Sep 19, 2017.
 */
public final class LoremIpsum {
    public static final String TEXT = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. " +
            "Duis malesuada ligula mauris, eget consectetur dolor rhoncus in. Fusce vulputate dui" +
            " sit amet elit laoreet elementum. Etiam aliquet, diam vel tincidunt iaculis, odio " +
            "ipsum convallis nunc, id laoreet lorem odio in tellus. Suspendisse fringilla sodales" +
            " ligula, volutpat ornare elit placerat vitae. Cras iaculis gravida ipsum, in tempus " +
            "eros laoreet in. Pellentesque nisl dolor, bibendum ac vehicula at, molestie et ex. " +
            "In hac habitasse platea dictumst. Aliquam sem lorem, lacinia nec urna at, tempor " +
            "fringilla lectus. Suspendisse potenti. Ut quis faucibus quam.\n" +
            "\n" +
            "Duis a arcu non leo placerat aliquam quis sed lectus. Class aptent taciti sociosqu " +
            "ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas non ex leo. " +
            "Sed luctus at diam at pulvinar. Aenean ut condimentum justo, sit amet luctus est. " +
            "Sed nisi purus, accumsan eu posuere id, fermentum sit amet diam. Praesent interdum " +
            "felis pretium suscipit placerat. Aenean a vehicula dui. Orci varius natoque " +
            "penatibus et magnis dis parturient montes, nascetur ridiculus mus.\n" +
            "\n" +
            "Fusce dignissim ut erat eget eleifend. Donec tristique nunc diam, quis blandit lacus" +
            " ornare at. Duis rhoncus nulla purus, nec gravida lorem efficitur sit amet. Sed nec " +
            "accumsan velit, vel pretium justo. Nullam dignissim ultricies nisl. Maecenas " +
            "malesuada vitae eros vitae tincidunt. Cras sed augue dictum, scelerisque orci sit " +
            "amet, vulputate tortor. In laoreet mauris lorem, in laoreet dui placerat vitae. " +
            "Morbi rutrum purus neque, sed consequat dui laoreet eget. Curabitur mattis et massa " +
            "nec porttitor. Donec pulvinar a quam at mattis. Phasellus feugiat est eget aliquet " +
            "pretium. Donec orci elit, lacinia et ex in, semper ultricies nisl.\n" +
            "\n" +
            "Mauris vel dapibus purus. Duis non semper turpis. Cras aliquam posuere lacus, eget " +
            "posuere enim tempus quis. Suspendisse condimentum, tellus vitae cursus ullamcorper, " +
            "lorem sapien congue lectus, in auctor orci lorem nec erat. Aenean viverra risus " +
            "tellus, gravida maximus libero ullamcorper ac. Sed id orci id eros consequat " +
            "molestie. Donec iaculis erat eget aliquam congue. Proin fringilla, lectus maximus " +
            "rutrum dapibus, diam lorem volutpat diam, in condimentum erat lorem ut ante.\n" +
            "\n" +
            "Sed dui tortor, interdum sit amet bibendum sed, maximus sed ante. Aliquam nec " +
            "scelerisque leo, in condimentum mauris. Lorem ipsum dolor sit amet, consectetur " +
            "adipiscing elit. Etiam congue elit in tincidunt aliquet. Vivamus erat felis, laoreet" +
            " sed tellus at, egestas lacinia odio. Pellentesque vitae facilisis tellus. Donec " +
            "porta arcu non dui lacinia, non vulputate leo eleifend. Mauris sit amet mauris " +
            "commodo nisl finibus luctus. Nullam vitae justo ac enim semper tempor.\n" +
            "\n" +
            "Suspendisse egestas dictum tellus, a dapibus leo suscipit eu. Quisque commodo tempor" +
            " blandit. Ut vehicula quis sem ut tempor. Donec posuere pellentesque vulputate. In " +
            "eu ex eget neque lobortis vehicula vitae eu turpis. Suspendisse potenti. Nam " +
            "porttitor efficitur enim, id vehicula risus sodales ac. Ut et enim nec justo " +
            "consequat gravida vitae vel risus. Praesent hendrerit consectetur eros eget ornare. " +
            "Proin pharetra ante vitae tellus ultricies commodo. Aenean at libero non risus " +
            "pellentesque porta id aliquet quam. Curabitur in dolor imperdiet, lobortis dolor eu," +
            " tempus elit. Sed metus sem, gravida at laoreet eget, aliquam nec metus. Sed rhoncus" +
            " turpis eu elit ornare, ut mollis libero luctus. Fusce pulvinar magna volutpat augue" +
            " mattis, in accumsan lorem ultrices.\n" +
            "\n" +
            "Donec mollis venenatis tellus. Phasellus quis viverra erat. Etiam ultrices ipsum a " +
            "dignissim finibus. Cras quis ligula ullamcorper, tempus erat eu, commodo nisi. Class" +
            " aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos " +
            "himenaeos. Cras est tortor, sodales gravida lectus nec, lacinia commodo tellus. Nam " +
            "dapibus sodales ipsum in porta. Donec eget diam placerat, luctus ligula ac, cursus " +
            "justo.\n" +
            "\n" +
            "Vestibulum est tortor, tristique nec semper ac, mollis vitae quam. Proin efficitur " +
            "felis sed massa vulputate, quis maximus urna viverra. Etiam molestie blandit ante, " +
            "in laoreet tortor fringilla in. Phasellus in ante diam. Suspendisse mi mi, luctus " +
            "quis mauris non, venenatis viverra quam. Lorem ipsum dolor sit amet, consectetur " +
            "adipiscing elit. Mauris risus arcu, semper in luctus ut, interdum eget mauris. Donec" +
            " malesuada orci mi, nec congue mi luctus quis. Vivamus placerat mi mauris, ut " +
            "laoreet diam scelerisque ac. Aenean et sem id dolor dictum blandit. Duis at lobortis" +
            " nibh. Vivamus cursus risus dui, sed lacinia erat commodo iaculis.\n" +
            "\n" +
            "Aenean gravida aliquet arcu, eu ultrices est gravida et. Orci varius natoque " +
            "penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec ut augue " +
            "consequat, scelerisque tellus sed, eleifend odio. Sed nec vehicula erat. Mauris nibh" +
            " dolor, ultrices vel risus at, congue sollicitudin sapien. Integer eu mattis augue. " +
            "Maecenas vitae venenatis lorem, sit amet finibus justo. Cras lacinia pellentesque " +
            "lorem, eget imperdiet massa rhoncus ac. Pellentesque eu sem at libero consequat " +
            "hendrerit quis sit amet quam. Curabitur convallis pretium molestie. Nunc placerat " +
            "elit eu dictum euismod. Suspendisse potenti.\n" +
            "\n" +
            "Nulla pellentesque nibh felis, sit amet ornare tortor pulvinar ac. Praesent id diam " +
            "ut erat fermentum commodo. Nam eu feugiat ligula, ac vulputate leo. Integer justo " +
            "quam, ultricies sed metus sit amet, pretium congue felis. Cras iaculis blandit " +
            "scelerisque. Proin faucibus nulla sem, ac hendrerit tellus iaculis sit amet. Nunc " +
            "vulputate pellentesque leo vitae dapibus. Fusce lacus mi, efficitur id diam sit " +
            "amet, mollis dictum lacus. Sed nec arcu a ante tempor dapibus. Duis ultrices odio at" +
            " erat tempus cursus.\n" +
            "\n" +
            "Sed rhoncus, arcu non porttitor feugiat, sem nibh ullamcorper neque, id rutrum leo " +
            "purus imperdiet velit. In hac habitasse platea dictumst. Etiam semper a purus ac " +
            "tincidunt. Mauris vulputate, velit vel ultrices ullamcorper, libero arcu ultrices " +
            "sapien, quis iaculis justo massa at neque. Praesent pellentesque tristique metus, " +
            "vel dictum odio. Cras vitae commodo massa, quis laoreet justo. Vestibulum fermentum " +
            "interdum diam non cursus. Proin quis elementum ante, id commodo nisl. Class aptent " +
            "taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. " +
            "Maecenas quis ante rutrum, condimentum nisi eget, placerat lacus. Donec a urna eu " +
            "justo maximus dictum. Praesent at vulputate orci. Quisque sit amet pellentesque diam" +
            ".\n" +
            "\n" +
            "Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos " +
            "himenaeos. Duis at auctor massa. Mauris iaculis iaculis ante, molestie pharetra urna" +
            " venenatis ac. Donec ac quam sed eros varius lacinia ornare ac nisi. Class aptent " +
            "taciti sociosqu ad litora torquent per.";
}
